#!/bin/bash

# Запрос имени
name=$(dialog --inputbox "Введите ваше имя:" 8 40 3>&1 1>&2 2>&3 3>&-)

# Проверка, что имя введено
if [ -z "$name" ]; then
    dialog --msgbox "Вы не ввели имя. Скрипт завершен." 7 40
    exit 1
fi

# Запрос профессии
profession=$(dialog --inputbox "Введите вашу профессию:" 8 40 3>&1 1>&2 2>&3 3>&-)

# Проверка, что профессия введена
if [ -z "$profession" ]; then
    dialog --msgbox "Вы не ввели профессию. Скрипт завершен." 7 40
    exit 1
fi

# Вывод имени и профессии
dialog --msgbox "Ваше имя: $name\nВаша профессия: $profession" 10 40

