#!/bin/bash

SRC="/home/youlchikk/lab13/source"
DEST="/home/youlchikk/lab13/destination"

inotifywait -m -r -e modify,create,delete,move "$SRC" --format '%w%f' | while read FILE
do
	rsync -avz "$SRC" "$DEST"
done

