#!/bin/bash

input_file="input.txt"
output_file="output.txt"

# Удаление всех символов, кроме буквенных
sed 's/[^a-zA-Z]//g' "$input_file" > "$output_file"

echo "Файл с только буквенными символами создан: $output_file"
